/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'difficulty' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'codeExample' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getLessonBySlug' : IDL.Func([IDL.Text], [Lesson], ['query']),
  'searchLessons' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'difficulty' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'codeExample' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getLessonBySlug' : IDL.Func([IDL.Text], [Lesson], ['query']),
    'searchLessons' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };